apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: grpc-demo
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: srinmantest.azurecr.io/grpc-client:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_ADDR
              value: "grpc-server:50051"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
